[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf

; Serial Monitor configuration
monitor_speed = 115200
monitor_filters = direct, esp32_exception_decoder

; Enforce custom partition table for OTA and NVS requirements
board_build.partitions = partitions.csv